//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TECres_WebApi_TEConstruye
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Propiedad = new HashSet<Propiedad>();
        }
    
        [DataMember]
        public int Cedula { get; set; }
        [DataMember]
        public string Nombre { get; set; }
        [DataMember]
        public string Apellido1 { get; set; }
        [DataMember]
        public string Apellido2 { get; set; }
        [DataMember]
        public int Telefono { get; set; }
        [DataMember]
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        [DataMember]
        public string Nacionalidad { get; set; }
        [DataMember]
        public Nullable<int> UbicacionUsuario { get; set; }
        [DataMember]
        public Nullable<int> Ingresos { get; set; }
        [DataMember]
        public Nullable<int> Ocupacion { get; set; }
        [DataMember]
        public string Correo { get; set; }
        [DataMember]
        public Nullable<int> Perfil { get; set; }
        [DataMember]
        public string Usuario { get; set; }
        
        public string Contraseña { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Propiedad> Propiedad { get; set; }
    }
}
