//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TECres_WebApi_TEConstruye
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class Propiedad
    {
        [DataMember]
        public int IDPropiedad { get; set; }
        [DataMember]
        public string Nombre { get; set; }
        [DataMember]
        public int UbicacionPropiedad { get; set; }
        [DataMember]
        public int Habitaciones { get; set; }
        [DataMember]
        public int Baños { get; set; }
        [DataMember]
        public int AreaTerreno { get; set; }
        [DataMember]
        public int AreaConstruccion { get; set; }
        [DataMember]
        public int Dueño { get; set; }
        [DataMember]
        public string Descripcion { get; set; }
        [DataMember]
        public Nullable<int> TipoInmueble { get; set; }
        [DataMember]
        public Nullable<int> TipoPisoProp { get; set; }
        [DataMember]
        public Nullable<int> Parqueos { get; set; }
        [DataMember]
        public string Gimnasio { get; set; }
        [DataMember]
        public string Piscina { get; set; }
        [DataMember]
        public string ParqueoVisitas { get; set; }
        [DataMember]
        public Nullable<int> Precio { get; set; }
        [DataMember]
        public string Foto1 { get; set; }
        [DataMember]
        public string Foto2 { get; set; }
        [DataMember]
        public string Foto3 { get; set; }
        [DataMember]
        public string Foto4 { get; set; }
        [DataMember]
        public string Foto5 { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
